### ISSUE TITLE
rename skills

### ISSUE THREAD

**Issue by ReK2Fernandez** [MycroftAI/mycroft-skills#133]
Suggestion: people should add in their skills if they work on the mark1 or desktop only etc... I see lot of confusing skill names.

**Comment by NimbleSloth** [comment]
I agree, the names need to be more clear! The list is a bit unruly, many people started thier skill names with "skill-XXXXX" so the alphabetized list of skills is messy.

**Comment by penrods** [comment]
Hey guys!  I haven't fully announced this publicly, but we've just put together a Skill Management Team consisting of me and four others from the community.  This very issue is basically the first thing we started talking about.  Due to the way things are connected to the mycroft-skill repo using submodules, we have the ability to "rename" skills without the author needing to do anything, so I think we will be able to retroactively do some cleanup on this, as well as create some guidelines to make it easier in the future.

I'm going to pull them all in to this issue.  Any input is appreciated!

   - Steve

@btotharye @el-tocino @AIIX @TREE-Edu
