### ISSUE TITLE
[Improvement] Home in languages other than English

### ISSUE THREAD

**Issue by denics** [MycroftAI/mycroft-skills#1342]
I am running on a picroft, but my suggestion applies to everybody happily using Mycroft in other languages

The home.mycroft.ai page is very useful for interacting with our installed skills. However it frustrate me a lot that all information reported there are limited and, in most cases, obsoletes when coming to "other languages".

My case:
I am Italian and I have configured Mycroft in Italian. Lot of fun, but it is very frustrating to see that the interface of my home.mycroft.ai is in English, and the suggested actions are in English (and the supported languages for skills are only English, which is not true).
If my Mycroft is Italian, you know it and so you should display my home with as much Italian as possible, so that I know what I should ask my assistant, without opening all vocab files to try to match the English intentions.

**Comment by krisgesling** [comment]
Hi Denics,

Thanks for raising this. Proper multilingual support is certainly something we want to work toward however we don't have the capacity internally to do so at the moment. As such Mycroft only officially supports English. 

Where we can, we support the community to contribute to language support including our [translation platform](https://translate.mycroft.ai), our multilingual parsing and formatting library [Lingua Franca](https://github.com/mycroftai/lingua-franca), and supporting a range of STT and TTS engines so that hopefully a service is available in your language. It's great to hear Mycroft is working well for you in Italian!

Off the top of my head, to provide multilingual support on home.mycroft.ai (aka Selene) we would need to:
- scrape all the text strings from Selene UI and sync it with our translation platform
- add the relevant UI elements to Selene to allow people to switch languages, and inject the text based on that language
- add language selection to the user onboarding process and send this to devices to update their config
- select a default STT, TTS configuration for each supported language.
- consider the best way of showing the languages supported by a Skill - is this a section in the README, a scrape of the vocab / dialog / locale sub-directories, or something else?

If you or anyone else reading along is interested in helping out on any of this, please let us know.

**Comment by forslund** [comment]
Project is no longer maintained, closing.
