### ISSUE TITLE
many skills missing

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/mycroft-skills#279]
This issues is intended as a reference list for skills missing in the repo, so they can be found, tested, potentially fixed and submitted

Does it need to be the skill maker submitting the skill to the repo?

i have found a few scattered skills, maybe abandoned, could someone else submit them?

should we reach out to the devs?

https://github.com/gerlachry/skill-bible
https://github.com/george-ai/skill-random-bible-verse
https://github.com/sm1th/mycroft-skill-bible

i also have a huge list of skills missing here, i am probably the major offender for this issue, please share any skills you know about that are missing here

leaving here for reference until i slowly do PRs for them

https://github.com/JarbasAl/skill-location-tracker
https://github.com/JarbasAl/skill-mashape
https://github.com/JarbasAl/skill-nutrients
https://github.com/JarbasAl/skill-face-recognition
https://github.com/JarbasAl/skill-camera
https://github.com/JarbasAl/skill-unified-news
https://github.com/JarbasAl/skill-countries
https://github.com/JarbasAl/skill-quotes
https://github.com/JarbasAl/skill-numbers
https://github.com/JarbasAl/skill-metal-archives
https://github.com/JarbasAl/skill-stephen-hawking
https://github.com/JarbasAl/skill-laugh
https://github.com/JarbasAl/skill-names
https://github.com/JarbasAl/cryptocoin_skill
https://github.com/JarbasAl/skill-how-to
https://github.com/JarbasAl/skill-konami-code
https://github.com/JarbasAl/fallback-rivescript
https://github.com/JarbasAl/fallback-jarbas
https://github.com/JarbasAl/fallback-node-red
https://github.com/JarbasAl/skill-dictation
https://github.com/JarbasAl/skill-browser
https://github.com/JarbasAl/fallback-selenium-cleverbot
https://github.com/JarbasAl/fallback-rivescript-universal
https://github.com/JarbasAl/skill-wiki-universal
https://github.com/JarbasAl/fallback-aiml-universal
https://github.com/JarbasAl/skill-joke-universal
https://github.com/JarbasAl/fallback-duckduckgo-universal
https://github.com/JarbasAl/skill-fallback-persona-universal
https://github.com/JarbasAl/fallback-wolfram-alpha-universal

+ a few in my old account im still migrating over and modernizing, for now ignore everything here: https://github.com/JarbasAI?tab=repositories

**Comment by AIIX** [comment]
I have a few skills which I have yet to submit a PR for as well but seeing my last submission is still stuck in waiting to merge so haven't really pushed the others.

- https://github.com/AIIX/open-library-skill - Search for ebooks by title/author name using OpenLibrary API
- https://github.com/AIIX/digikam-control -  control the DigiKam application
- https://github.com/AIIX/ask-stack - Find and Ask Stack Overflow Questions
- https://github.com/AIIX/image-ocr-skill - Image OCR skill for Mycroft on KDE Plasma 
- https://github.com/AIIX/plasma-baloo-search-skill - Baloo-search for finding locally indexed files like Audio/Video/Images/Documents/Spreadsheets/Archives on Plasma-desktop 
- https://github.com/AIIX/skill-stock - Fork of stock skill with HTML display stuff
- https://github.com/AIIX/skill-weather - Fork of weather skill with HTML/QML display stuff

**Comment by AIIX** [comment]
I think this issue should be rather expanded to the skills in master not in 18.02 and previous skill authors need to contacted to resubmit their skills to the new branch, Additionally as a skill owner who has submitted skill to 18.02 branch but is still awaiting in PR request due to skill-testing not working on desktop platform skills because of missing X11 and dbus integration in auto skill test for multiple platforms I'd request this issue to remain open, and as a side effect of this I can't push in other skills of mine as well due to the current skill stuck in PR. Reference: https://github.com/MycroftAI/mycroft-skills/pull/336

**Comment by btotharye** [comment]
Well that seems stupid to not put your skill into the repo just cause their tests are broke.  I have for now built my own seperate unittests from the test runner because I had issues with it working on travis and updating my coverage.  I was just trying to play cleanup on some of these old issues that are sitting out that don't seem to be any value add atm except from taking away from real issues.

**Comment by forslund** [comment]
Project is unmaintained, closing.
