### ISSUE TITLE
REQ: twitter skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#44]
requesting a twitter skill, i dont use twitter but if mycroft did i would start to....

features:
- tweet something 

"hey mycroft, start tweeting"

beep,wait for sound "this is test tweet", silence detected(or maybe wait for stop tweeting), beep, speak "tweeted" 

- read tweets from

not sure on the workflow of this

**Comment by blackfireburn** [comment]
https://dev.twitter.com/overview/api
cert validation in python 
https://stackoverflow.com/questions/1087227/validate-ssl-certificates-with-python
https://dev.twitter.com/overview/api/tweets


https://stackoverflow.com/questions/10719714/python-how-to-post-statuses-update-with-media-to-twitter#11442747


would there be a way to end the command rather than waiting? as the timeout required could be too arbitrary.

**Comment by marksev1** [comment]
+1 for this skill :).

**Comment by JarbasAI** [comment]
it seems work has been done on this

https://github.com/MycroftAI/mycroft-core/blob/feature/twitter/mycroft/skills/twitter/__init__.py

**Comment by marksev1** [comment]
This seems to be just for posting...not nearly enough functionality, but yeah its a start :).

**Comment by btotharye** [comment]
This is already done and I am updating it every few days, https://github.com/btotharye/mycroft-twitter-skill

**Comment by btotharye** [comment]
Closing this issue there is a twitter skill and if there are updates need PR's can be submitted to https://github.com/btotharye/mycroft-twitter-skill
