### ISSUE TITLE
Choosing preposition/case for location in weather skill

### ISSUE THREAD

**Issue by ftyers** [MycroftAI/mycroft-skills#624]
This is a placeholder issue for a problem for the problem of choosing the right preposition or case for a locative in different languages in the weather skill. 

The issue is as follows:

```För närvarande är det {{condition}} och {{temp}} grader {{scale}} i {{location}}.```

Consider this Swedish example, where "location" is "Gotland" it might be more idiomatic to use "på" not "i".

It is more complicated for other languages, for example for Finnish, most places take inessive *Helsinki* "Helsinki" -- *Helsingissä* "in Helsinki", but some take adessive *Tampere* "Tampere" -- *Tamperella* "in Tampere". Also note that currently there seems to be no way to inflect words or provide inflected forms (see Finnish examples).

I have some ideas on how to fix this and at the same time make the output more idiomatic, I'll get back to it soon.

**Comment by forslund** [comment]
Hej,

First an aside:
When I did this translation I chose the `i {{location}}` since the skill mainly deals in cities.

Secondly you definitely have point here and this will have to be resolved. As language support is only just gearing up with the new https://translate.mycroft.ai site this will become even more important in the near future.

I'm very much looking forward to your proposed solution. If this is something general that should be in mycroft-core as part of the language specific formatting code there maybe you should move the issue there.

**Comment by ftyers** [comment]
@forslund yeah, that makes sense, I just gave that example because it might have been more intelligible to get an idea than the Finnish example :) ... I'll write to you off the issues because I think that `.po` might not be the best format for this, but don't want to explain it all at once.

**Comment by forslund** [comment]
@ftyers @KathyReid is leading the internationalization and would probably love to discuss this in detail. I believe she has a bit of experience in the field and can probably understand your ideas/thoughts better than me.

(I'm just a code-monkey, I'll just try to throw a regex at any language problem ;) )

**Comment by forslund** [comment]
Project is unmaintained, closing.
