### ISSUE TITLE
REQ - Red Alert skill

### ISSUE THREAD

**Issue by JarbasAI** [MycroftAI/mycroft-skills#64]
this is analogous to mycroft calling 911

general skeleton for red alert:
- emergency contact list
     - facebook
     - sms
     - sip service
      - the more the better
- periodic resending until deactivating
- after 10 missed responses start public calls for help (facebook wall posts?)
- mute speech and start recording both audio and video (murder case evidence)

**Comment by MrGrymReaper** [comment]
> mute speech and start recording both audio and video (murder case evidence)

Will need to meet the requirements so that law enforcement and judiciary can accept it as evidence. Otherwise that feature won't be of use if it doesn't meet the requirements.

For United Kingdom these website have the requirements:- https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part32
http://www.hse.gov.uk/enforce/enforcementguide/court/rules-intro.htm

For EU:-
https://e-justice.europa.eu/content_evidence-92-en.do
http://ec.europa.eu/justice/criminal/law/index_en.htm

As well as speaking to a lawyer and asking about the requirements for the recordings to be accepted auditory and video graphic evidence by law enforcement and the judiciary system.

**Comment by MrGrymReaper** [comment]
@JarbasAI For the United Kingdom it would be the equivalent to Mycroft calling "999". As it is the emergency number for the UK. And from the documentaries and reading online that it is the number you specified for the United States.

There would be different numbers for emergency operator phone calls internationally in different countries.

**Comment by MrGrymReaper** [comment]
> emergency contact list 

It is important that the emergency contact list is carefully setup by the user and not just everyone is dumped on this list. As there could be some individuals otherwise that may get the notification who shouldn't be getting it.

Who worse could be the ones involved as part of the feature specified in:-

> mute speech and start recording both audio and video (murder case evidence)

They could come along and stop the red alert skill.

**Comment by MrGrymReaper** [comment]
@el-tocino Please add a tag for "Lawyer" or "Solicitor" legal advice required. As there are evidence requirements information needed for one feature of this skill.

**Comment by JarbasAI** [comment]
the emergency number should be set by the user, so it could choose to call someone else instead, and have a default maybe derived from the location setting?

in my case it would be 112 :)

**Comment by MrGrymReaper** [comment]
@JarbasAI A phone number is considered a personal detail under EU's GDPR. So not only do you need to get permission but also store it securely. In order to be compliant with the regulation. So read up on the regulation as the contact list are personal details.

**Comment by MrGrymReaper** [comment]
@JarbasAI You would also need an account along with authentication details configured so that the phone number calls can be made through VoIP or other internet enabled phone services.

**Comment by el-tocino** [comment]
GDPR applies to companies.  If an individual is installing a locally hosted skill on their own equipment, that wouldn't be covered, it would be fairly equivalent to installing an app that has no uploading of data. If a skill connects to a third-party that handles personal data storage, then the 3rd party would be the responsible entity for meeting regulations.

**Comment by KathyReid** [comment]
Hi there @JarbasAI  thanks so much for raising this as a request. 
We've now moved all our our Skill Suggestions / requests to 
https://community.mycroft.ai/c/skill-suggestions
Apologies for the extra work, but could I request that you write up this Skill Suggestion there? 
That way our community is able to vote on it.
Kind regards, 
Kathy
